name: Testing Deployment

on:
  push:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  test_deployment:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Get timestamp
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop'  || startsWith(github.ref, 'refs/tags/v')) }}
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop'  || startsWith(github.ref, 'refs/tags/v')) }}
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      - name: Generate deployment package
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/develop'  || startsWith(github.ref, 'refs/tags/v')) }}
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY_ID }}
          application_name: "testing-docker-deployment"
          environment_name: "Testing-docker-deployment-env"
          version_label: "test-${{ steps.format-time.outputs.replaced }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
